[package]
name = "bdk_workshop"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_esplora = { version = "=0.16.0", features = ["blocking"] }
bdk_wallet = { version = "=1.0.0-beta.1", features = ["keys-bip39"] }
